### PR TITLE
Update Android plugin to Capacitor 5

### PR DESCRIPTION
**Pull request by chrisweight-elsewhen**
Updates gradle properties in line with https://capacitorjs.com/docs/next/updating/plugins/5-0

### CODE REVIEW

**Comment by mraible** [comment]
Thanks for creating this! I ran into this issue today when I tried to upgrade @oktadev/schematics to use Capacitor 5. 

https://github.com/oktadev/schematics/pull/1092

**Comment by leonluc-dev** [comment]
This is still missing two required changes for migration:

* Changing Java version from 11 to 17
* Updating package.json to include the new Capacitor npm dependencies

I've opened a PR that should add these changes to your fork, so they can be added to this PR.

**Comment by chrisweight-elsewhen** [comment]
> This is still missing two required changes for migration:
> 
> * Changing Java version from 11 to 17
> * Updating package.json to include the new Capacitor npm dependencies
> 
> I've opened a PR that should add these changes to your fork, so they can be added to this PR.

merged that, cheers :)

**Comment by mraible** [comment]
It'd be awesome if this could be merged and a new release published.

**Comment by martinkasa** [comment]
Hi all, 

many thanks for this PR, it was really helpful for people playing with v5 before official release. Since I wanted to have whole migration of plugin (iOS and Android) and Test app, I have updated all at once by Ionic's migration scripts. Tests passed successfully, I tried manually test by test app, so I hope everything works as expected.

This PR was just merged, and v0.9.0 published.

https://github.com/martinkasa/capacitor-secure-storage-plugin/pull/79

**Pull request closed without merging**
