### PR TITLE
Upgrade to Capacitor v4

### PR DESCRIPTION
**Pull request by de-dan**
PR for #58

### CODE REVIEW

**Comment by richardkshergold** [comment]
Looking forward to this PR being merged as we are wanting to migrate our app to Capacitor V4.  Thanks!

**Comment by Chuckv01** [comment]
@martinkasa merge and publish this pretty please?

**Comment by NikSteel** [comment]
Looking forward to this update as well 🙂

**Comment by AliMejbar** [comment]
Tested it and it works fine for me , looking forward for the merge !

**Comment by martinkasa** [comment]
@de-dan Thank you for this nice and complete PR. I am sorry for merging this so late. I have tested iOS, but I did not manage to test Android, so I hope it is working as well :)

**Comment by mraible** [comment]
Is it possible to get a new release with this fix? 

I tried to integrate it with the following in my `package.json`:

```json
  "overrides": {
    "capacitor-secure-storage-plugin": "martinkasa/capacitor-secure-storage-plugin"
  }
```

However, when I run `ionic build`, I get a compile error.

```
./node_modules/ionic-appauth/lib/capacitor/capacitor-secure-storage.js:2:0-70 - Error: Module not found: 
Error: Can't resolve 'capacitor-secure-storage-plugin' in '/.../ionic-app/node_modules/ionic-appauth/lib/capacitor'
```

**Comment by mraible** [comment]
I was able to get past the issue above. Now I just need a release of this library to add Capacitor 4 support to Ionic AppAuth. Pretty please? 😊

**Comment by martinkasa** [comment]
Hi @mraible, version 0.8.0 with Capacitor v4 support was released few day ago. I am not sure what do you need to be honest :)

**Comment by mraible** [comment]
I'm sorry, I didn't realize a release was available because I didn't see anything under [releases](https://github.com/martinkasa/capacitor-secure-storage-plugin/releases) or [tags](https://github.com/martinkasa/capacitor-secure-storage-plugin/tags). Thank you!

**Comment by martinkasa** [comment]
Yeah.. sorry for confusion. I used "release-it" package before, but after reinstallation of my laptop I have not installed it again and release the package simply by npm publish, which do not create github release. But thanks for feedback, I will try to not forget to use it in future.

**Pull request merged**
